manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: elepkenin
      url-base: https://github.com/elepkenin
    - name: joelspadin
      url-base: https://github.com/joelspadin
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-userspace
      remote: elepkenin
      revision: main
    - name: zmk-locales
      remote: joelspadin
      revision: main
  self:
    path: config

